In [1]:
import sys
import os

# Add the parent directory (project root) to sys.path
project_root = os.path.abspath(os.path.join(os.getcwd(), "../.."))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Randomness

## JAX

In [3]:
from general_python.algebra.utils import get_backend as __backend
from general_python.algebra.ran_wrapper import uniform, randint
# test random
seed    = None
backend = 'np'
for i in range(5):
    modules = __backend(backend, random=True, seed=seed)
    backend, (rnd_module, key) = modules if isinstance(modules, tuple) else (modules, (None, None))
    print(f"backend: {backend}")
    print(f"key: {key}")
    print(f"rnd_module: {rnd_module}")
    print(f"rnd_module.random(): {rnd_module.random()}")
    print(f"rnd_module.randint(0, 10): {rnd_module.integers(0, 10)}")
    print(f"rnd_module.uniform(0, 10): {rnd_module.uniform(0, 10)}")
    print(f"rnd_module.normal(0, 1): {rnd_module.normal(0, 1)}")
    # take the function from random wrapper
    print(f"uniform(0, 10): {uniform(shape=(5,),minval=0, maxval=10, backend=backend, seed=seed)}")
    print()

backend: <module 'numpy' from '/Users/makskliczkowski/miniconda3/lib/python3.12/site-packages/numpy/__init__.py'>
key: None
rnd_module: Generator(PCG64)
rnd_module.random(): 0.9034540068082391
rnd_module.randint(0, 10): 9
rnd_module.uniform(0, 10): 2.5707417527653433
rnd_module.normal(0, 1): -1.1082144670930707
uniform(0, 10): [2.58853399 3.5544648  0.05022334 6.28604544 2.82382707]

backend: <module 'numpy' from '/Users/makskliczkowski/miniconda3/lib/python3.12/site-packages/numpy/__init__.py'>
key: None
rnd_module: Generator(PCG64)
rnd_module.random(): 0.06808768948794575
rnd_module.randint(0, 10): 5
rnd_module.uniform(0, 10): 1.7632632028120343
rnd_module.normal(0, 1): 0.618350014800829
uniform(0, 10): [4.40886811 1.50202341 2.17928863 4.74333115 4.76368855]

backend: <module 'numpy' from '/Users/makskliczkowski/miniconda3/lib/python3.12/site-packages/numpy/__init__.py'>
key: None
rnd_module: Generator(PCG64)
rnd_module.random(): 0.25523235381950027
rnd_module.randint(0, 10): 6
rnd_

# Models

## Quantum Sun Model

In [2]:
from Algebra.Model.Interacting.Spin.qsm import QSM
backend = 'np'
hamil=QSM(ns=11, hilbert_space=None, n=3, a=0.74, h=1.0, xi=0.2, backend='np', dtype='float64')
hamil.h

=== Backend Initialization ===
	NumPy Version: 1.26.4
	SciPy Version: 1.13.1
	JAX Version: Not Available
		Active Backend: jax
		JAX Available: True
		Default Random Key: [    0 12345]
	Active Backend Modules:
			Main Module: <module 'jax.numpy' from '/Users/makskliczkowski/miniconda3/lib/python3.12/site-packages/jax/numpy/__init__.py'>
			Random Module: <module 'jax.random' from '/Users/makskliczkowski/miniconda3/lib/python3.12/site-packages/jax/random.py'>
			SciPy Module: <module 'jax.scipy' from '/Users/makskliczkowski/miniconda3/lib/python3.12/site-packages/jax/scipy/__init__.py'>
=== End of Backend Info ===


ImportError: cannot import name 'HilbertSpace' from partially initialized module 'Algebra.hilbert' (most likely due to a circular import) (/Users/makskliczkowski/Codes/QuantumEigenSolver/Python/QES/Algebra/hilbert.py)

#### Build

##### Sparse

In [ ]:
hamil.build(verbose=True, use_numpy=True)
print(f"Memory:{hamil.memory_gb:.3e}gb")

In [ ]:
hamil.diagonalize(verbose=True)

In [ ]:
hamil.eig_val

##### Dense

In [ ]:
qsm.to_dense()

In [ ]:
qsm.build(verbose=True, use_numpy=True)

In [ ]:
qsm.diagonalize(verbose=True)

In [ ]:
qsm.h_memory_gb

##### Plot tests

In [ ]:
import matplotlib.pyplot as plt
plt.plot(hamil.eig_val)
hamil.eig_val, hamil.eig_vec, hamil.eig_vec.shape

In [ ]:
import numpy as np
# make dense
qsm_dense   = qsm.hamil.todense() if qsm.sparse else qsm.hamil
minimum     = qsm_dense.min()
maximum     = qsm_dense.max()
qsm_dense   = np.abs(qsm_dense) / np.abs(qsm_dense).max()

print("Minimum value:", minimum)
print("Maximum value:", maximum)

plt.figure(figsize=(5, 5))
plt.imshow(qsm_dense, cmap='viridis')
plt.colorbar()
plt.title("Density Representation")
plt.show()

##### Operators

In [ ]:
from Algebra.Operator.operators_spin import sig_x, sig_z, OperatorTypeActing
from general_python.common import binary
import numpy as np

backend     = 'np'
ns          = 4
nh          = 2**ns   
sig_x_op = sig_x(ns = ns, type_act = OperatorTypeActing.Global, sites = [ns - 1], backend=backend)
sig_z_op = sig_z(ns = ns, type_act = OperatorTypeActing.Global, sites = [ns - 1], backend=backend)
eye_first   = np.eye(2**(ns - 1))
eye_first

###### Check how it works on the base states

###### With states

In [ ]:
int_state_full      = 2**(ns) - 1
int_state_half      = 2**(ns - 1) - 1
int_state_half_size = 2**(ns//2) - 1

# binary representation
backend_state           = binary.int2base(int_state_full, size=ns, backend=backend)
backend_state_half      = binary.int2base(int_state_half, size=ns, backend=backend)
backend_state_half_size = binary.int2base(int_state_half_size, size=ns//2, backend=backend)
# string representation
string_state            = binary.int2binstr(int_state_full, bits=ns)
string_state_half       = binary.int2binstr(int_state_half, bits=ns)
string_state_half_size  = binary.int2binstr(int_state_half_size, bits=ns)

# act on the integer states
for state in [int_state_full, int_state_half, int_state_half_size]:
    print()
    # sigma x
    print("Applying sigma_x")
    print(f"Acting on state {state} ({binary.int2binstr(state, bits=ns)})")
    resulting_state, resulting_value = sig_x_op(state)
    print(f"Resulting state: {resulting_state[0]}")
    print(f"Resulting value: {resulting_value}")
    print(f"Binary representation of resulting state: {binary.int2binstr(resulting_state[0], bits=ns)}")
    # sigma z
    print("Applying sigma_z")
    resulting_state, resulting_value = sig_z_op(state)
    print(f"Resulting state: {resulting_state[0]}")
    print(f"Resulting value: {resulting_value}")
    print(f"Binary representation of resulting state: {binary.int2binstr(resulting_state[0], bits=ns)}")
    print()


In [ ]:
from Algebra.Operator.operators_spin import _SIG_X, _SIG_Z, _SIG_0

sig_x_op_mat = sig_x_op.matrix(dim = nh, matrix_type = 'sparse', use_numpy = True)
sig_x_op_mat_kron = np.kron(eye_first, _SIG_X * 0.5)
sig_z_op_mat = sig_z_op.matrix(dim = nh, matrix_type = 'sparse', use_numpy = True)
sig_z_op_mat_kron = np.kron(eye_first, -_SIG_Z * 0.5)

# compare the two
is_equal = np.allclose(sig_x_op_mat.todense(), sig_x_op_mat_kron)
print("Are the two matrices (sig_x) equal?", is_equal)
is_equal = np.allclose(sig_z_op_mat.todense(), sig_z_op_mat_kron)
print("Are the two matrices (sig_z) equal?", is_equal)

if nh < 64:
    from general_python.common.plot import MatrixPrinter
    print("From the operator (sig_x)")
    MatrixPrinter.print_matrix(sig_x_op_mat.todense())
    print("From the operator (sig_z)")
    MatrixPrinter.print_matrix(sig_z_op_mat.todense())
    print("From tensor (sig_x)")
    MatrixPrinter.print_matrix(sig_x_op_mat_kron)
    print("From tensor (sig_z)")
    MatrixPrinter.print_matrix(sig_z_op_mat_kron)

###### With Hamiltonian

###### Matrix

In [ ]:
from general_python.algebra.linalg import act, overlap
from general_python.common.plot import Plotter, colorsCycle
from general_python.maths.statistics import Statistics, HistogramAverage, Fraction
from Algebra.Operator.operators_spin import sig_x, sig_z, OperatorTypeActing
import matplotlib.pyplot as plt
from tqdm import tqdm

dtype           = 'float64'
nrealizations   = (np.array([100, 100, 100, 50, 30, 20])/5).astype(int)
alpha           = 0.86
histograms_x    = {}
histograms_z    = {}
diagonals_x     = {}
diagonals_z     = {}
energies        = {}
nss             = [6,7,8,9]

# nss             = [9,10,11]
# nrealizations   = [10]

def set_histogram(hamiltonian, hist_sig_x: HistogramAverage, hist_sig_z: HistogramAverage, nbins):
    bandwidth       = hamiltonian.get_bandwidth()
    omax            = bandwidth * 3
    omin            = 0.01 / hamiltonian.hilbert_size
    tolerance       = 0.02 * bandwidth
    hist_sig_x.reset(nbins=nbins)
    hist_sig_x.uniform_log(v_max=omax, v_min=omin)
    hist_sig_z.reset(nbins=nbins)
    hist_sig_z.uniform_log(v_max=omax, v_min=omin)
    return tolerance

for ii, ns in enumerate(nss):
    realizations    = nrealizations[ii] if ii < len(nrealizations) else nrealizations[-1]
    energies[ns]    = []
    diagonals_x[ns] = []
    diagonals_z[ns] = []
    nh              = 2**ns
    sites           = [ns - 1]
    # sites           = [0]
    sig_x_op        = sig_x(ns = ns, type_act = OperatorTypeActing.Global, sites = sites, backend=backend)
    sig_z_op        = sig_z(ns = ns, type_act = OperatorTypeActing.Global, sites = sites, backend=backend)
    sig_x_op_mat    = sig_x_op.matrix(dim = nh, matrix_type = 'sparse', use_numpy = True)
    sig_z_op_mat    = sig_z_op.matrix(dim = nh, matrix_type = 'sparse', use_numpy = True)
    histogram_sig_x = HistogramAverage(dtype=dtype)
    histogram_sig_z = HistogramAverage(dtype=dtype)
    nbins           = int(20 * np.log2(nh))
    tolerance       = 0.0
    for realization in tqdm(range(realizations)):
        # print(f"Realization {realization + 1}/{nrealizations}")
        hamil       = QSM(ns=ns, hilbert_space=None, n=3, a=alpha, h=1.0, xi=0.2, backend = 'np', dtype='float64')
        hamil.build(verbose=False, use_numpy=True)
        hamil.diagonalize(verbose=False)
        states      = hamil.eig_vec
        eigvals     = hamil.eig_val
        sig_x_elems = overlap(states, states, sig_x_op_mat, backend = backend)
        sig_z_elems = overlap(states, states, sig_z_op_mat, backend = backend)
        diag_sig_x  = sig_x_elems.diagonal()
        diag_sig_z  = sig_z_elems.diagonal()
        if realization == 0:
            tolerance = set_histogram(hamil, histogram_sig_x, histogram_sig_z, nbins)
        # get the average energy
        energy_at       = hamil.av_en
        # create the f_functions by taking the middle spectrum (%)
        w, i_idx, j_idx = Fraction.spectral_function_fraction(eigvals, energy_at, tolerance)
        # ones            = np.ones_like(sig_x_elems)
        # ones[i_idx, j_idx] = 0
        # plt.imshow(ones)
        # fill the histogram
        sig_x_changed   = np.abs(sig_x_elems[i_idx, j_idx])**2
        sig_z_changed   = np.abs(sig_z_elems[i_idx, j_idx])**2
        histogram_sig_x.append(w, np.abs(sig_x_elems[i_idx, j_idx])**2)
        histogram_sig_z.append(w, np.abs(sig_z_elems[i_idx, j_idx])**2)
        diagonals_x[ns].append(diag_sig_x)
        diagonals_z[ns].append(diag_sig_z)
        energies[ns].append(eigvals)
    histograms_x[ns] = histogram_sig_x
    histograms_z[ns] = histogram_sig_z
    

In [ ]:
from general_python.physics.eigenlevels import gap_ratio
fig, ax     = Plotter.get_subplots(nrows=2, ncols=2, sizex=5, sizey=5, dpi=150)

# plot
for ii, ns in enumerate(energies.keys()):
    realizations = nrealizations[ii] if ii < len(nrealizations) else nrealizations[-1]
    nh          = 2**ns
    x           = energies[ns][0] / ns
    # x           = np.arange(nh)
    colors1, _, _= Plotter.get_colormap(nss, cmap='viridis')
    colors2, _, _= Plotter.get_colormap(nss, cmap='plasma_r')
    color1      = colors1(ns)
    color2      = colors2(ns)
    Plotter.scatter(ax[0], x, diagonals_x[ns][0], label=f'$L={ns}$', color=color1)
    Plotter.scatter(ax[1], x, diagonals_z[ns][0], label=f'$L={ns}$', color=color2)
    Plotter.set_ax_params(ax[0], xlabel='i/L', ylabel=r'$O_{ii}$', title='$\sigma_x$')
    Plotter.set_ax_params(ax[1], xlabel='i/L', ylabel=r'$O_{ii}$', title='$\sigma_z$')

    Plotter.scatter(ax[2], histograms_x[ns].bin_edges, histograms_x[ns].averages_av()*nh, label=f'$L={ns}$', color=color1)
    Plotter.scatter(ax[3], histograms_z[ns].bin_edges, histograms_z[ns].averages_av()*nh, label=f'$L={ns}$', color=color2)
    Plotter.set_ax_params(ax[2], xlabel=r'$\omega$', 
        ylabel=r'$\mathcal{D}|O_{ij}|^2$', scale={'x': 'log', 'y': 'log'})
    Plotter.set_ax_params(ax[3], xlabel=r'$\omega$', 
        ylabel=r'$\mathcal{D}|O_{ij}|^2$', scale={'x': 'log', 'y': 'log'})
    gap_ratios = [gap_ratio(energies[ns][i])['mean'] for i in range(realizations)]
    print(f"ns = {ns}, gap_ratio = {np.mean(gap_ratios)}")
    Plotter.set_legend(ax[2])
fig.tight_layout()

In [ ]:

d_en = np.diff(energies[8])
d_en = d_en / np.mean(d_en)
gap_ratios = np.minimum(d_en[:-1], d_en[1:]) / np.maximum(d_en[:-1], d_en[1:])
print(np.mean(gap_ratios))


# Linear algebra

In [ ]:
import general_python.algebra as algebra
a = algebra.AlgebraTests(backend='jax')
b = algebra.AlgebraTests(backend='numpy')

## Standard tests

### Change the basis with a unitary matrix

In [ ]:
a.change_basis(verbose=True)
b.change_basis(verbose=True)

### Change the basis of a matrix with a unitary matrix

In [ ]:
a.change_basis_matrix(verbose=True)

### Outer product

In [ ]:
a.outer(verbose=True)
b.outer(verbose=True)

### Kronecker product

In [ ]:
a.kron(verbose=True)

## Linear solvers

In [ ]:
a = algebra.SolversTests(backend='numpy')
b = algebra.SolversTests(backend='jax')

In [ ]:
a.solver_test()

# Binary 

### Standard tests

In [ ]:
from general_python.common import binary
NUM         = 42
tests       = binary.BinaryFunctionTests()

In [ ]:
tests.run_tests(NUM, spin_value = binary._BACKENDREPR)

In [ ]:
tests.run_tests(NUM, spin_value = binary._BACKENDREPR, backend = 'np')

### Test JAX

In [ ]:
from algebra import get_backend
import time 
from jax import numpy as jnp, random as jnpr
import numpy as np, numpy.random as npr
from jax import jit

seed = 1701

# Test the speed of the matrix multiplication
key_np = npr.seed(seed)
key_jnp = jnpr.key(seed)
size = 5000

def matrix_mult_test_jax(size=size):
    random_mat  = jnpr.normal(key_jnp, (size, size))
    vec         = jnpr.normal(key_jnp, (size,))
    result      = random_mat @ vec
    print("Result of matrix-vector multiplication:\n", result)
    
def matrix_mult_test_numpy(size = size):
    random_mat  = npr.normal(size=(size, size))
    vec         = npr.normal(size=(size,))
    result      = random_mat @ vec
    print("Result of matrix-vector multiplication:\n", result)
    
@jit
def matrix_mult_test_jax_jit():
    random_mat  = jnpr.normal(key_jnp, (size, size))
    vec         = jnpr.normal(key_jnp, (size,))
    result      = random_mat @ vec
    print("Result of matrix-vector multiplication:\n", result)


#### Numpy

In [ ]:
start_time = time.time()
matrix_mult_test_numpy()
end_time = time.time()
print(f"Time taken: {end_time - start_time:.4f} seconds (numpy)")

#### Jax

In [ ]:
start_time = time.time()
matrix_mult_test_jax()
end_time = time.time()
print(f"Time taken: {end_time - start_time:.4f} seconds (jax)")

#### Jax jit

In [ ]:
start_time = time.time()
matrix_mult_test_jax_jit()
end_time = time.time()  
print(f"Time taken: {end_time - start_time:.4f} seconds (jax, jitted)")

# Lattice


In [ ]:
from lattices import Lattice, run_lattice_tests

# Run tests for different configurations
# run_lattice_tests(dim=1, lx=10, ly=1, lz=1, bc=lattices.LatticeBC.PBC, typek="square")
# run_lattice_tests(dim=2, lx=5, ly=3, lz=1, bc=lattices.LatticeBC.PBC, typek="square")
# run_lattice_tests(dim=2, lx=5, ly=5, lz=1, bc=lattices.LatticeBC.OBC, typek="square")
# run_lattice_tests(dim=3, lx=3, ly=3, lz=3, bc=lattices.LatticeBC.PBC, typek="square")
run_lattice_tests(dim=2, lx=3, ly=2, lz=1, bc=lattices.LatticeBC.PBC, typek="honeycomb")

In [ ]:
import numpy as np 
import matplotlib.pyplot as plt

plt.figure(figsize=(8,8))

a = 1
b = 1
c = 1

Lx = 4
Ly = 2
Ns = 2 * Lx * Ly

_a1 = np.array([np.sqrt(3) * a / 2.0, 3 * a / 2.0, 0])
_a2 = np.array([np.sqrt(3) * a / 2.0, -3 * a / 2.0, 0])
_a3 = np.array([0, 0, c])



coords      = []
move_vector = _a1 - np.array([0, a, 0])
for i in range(Ns):
    # get the unit cell on a square lattic
    x = (i // 2) % Lx
    y = ((i//2) // Lx) % Ly
    
    # from coorditates to position on the lattice
    xy = np.array([0., 0, 0]) if i % 2 == 0 else move_vector
    xy += x * (_a1 + _a2) + y * _a1
    xp, yp = xy[0], xy[1]
    print(xp, yp)
    plt.scatter(xp, yp, color='red' if i % 2 == 0 else 'blue', marker='o', s=100, facecolor='none')
    plt.text(xp + 0.1, yp + 0.1, i)
    
    print("Ns=", i, "-- (x,y)=", x, y)


plt.arrow(0, 0, _a1[0], _a1[1], head_width=0.1, head_length=0.1, fc='r', ec='r')
plt.arrow(0, 0, _a2[0], _a2[1], head_width=0.1, head_length=0.1, fc='b', ec='b')
# plt.arrow(0, 0, _a1[0] - _a2[0], _a1[1] - _a2[1], head_width=0.1, head_length=0.1, fc='g', ec='g')
# plt.arrow(0, 0, _a1[0] + _a2[0], _a1[1] + _a2[1], head_width=0.1, head_length=0.1, fc='y', ec='y')
# plt.arrow(0, 0, -_a1[0] + _a2[0], -_a1[1] + _a2[1], head_width=0.1, head_length=0.1, fc='m', ec='m')
# plt.arrow(0, 0, -_a1[0] - _a2[0], -_a1[1] - _a2[1], head_width=0.1, head_length=0.1, fc='c', ec='c')


# NQS

## Sampler

In [1]:
import Solver.MonteCarlo.sampler as Sampling
from general_python.algebra.utils import get_backend
from general_python.ml.net_impl.net_simple import SimpleNet

import random
import numpy as np

# get random backend
backend     = 'np'
seed        = 1701
be_modules  = get_backend(backend, random=True, seed=seed, scipy=True)
backend_np, (rng, rng_k), backend_sp = be_modules if isinstance(be_modules, tuple) else (be_modules, (None, None), None)

ns                  = 10
st_shape            = (ns, )
activations         = ('relu', 'sigmoid')
net                 = SimpleNet(act_fun =   activations, 
                        input_shape     =   st_shape, 
                        output_shape    =   (1, ),
                        layers          =   (5, ),
                        backend=backend, dtype='complex128',)
            # [random.random() + 1j * random.random() for _ in range(x.shape[0])])
# a simple callable network function

sampler = Sampling.MCSampler(
    net         = net,
    shape       = st_shape,
    rng         = rng,
    rng_k       = rng_k,
    numchains   = 10,
    numsamples  = 5,
    sweep_steps = 10,
    backend     = backend,
    therm_steps = 10,
)

sampler

=== Backend Initialization ===
	NumPy Version: 1.26.4
	SciPy Version: 1.13.1
	JAX Version: Not Available
		Active Backend: jax
		JAX Available: True
		Default Random Key: [    0 12345]
	Active Backend Modules:
			Main Module: <module 'jax.numpy' from '/home/klimak/libraries/anaconda3/lib/python3.11/site-packages/jax/numpy/__init__.py'>
			Random Module: <module 'jax.random' from '/home/klimak/libraries/anaconda3/lib/python3.11/site-packages/jax/random.py'>
			SciPy Module: <module 'jax.scipy' from '/home/klimak/libraries/anaconda3/lib/python3.11/site-packages/jax/scipy/__init__.py'>
=== End of Backend Info ===


MCSampler(shape=(10,), mu=2.0, beta=1.0, therm_steps=10, sweep_steps=10, numsamples=5, numchains=10, backend=np)

In [2]:
# check how the sampler performs
(states, logprobas), (configs, configs_ansatze), probabilities = sampler.sample()

In [3]:
# final states after sampling, ansatze after sampling
states.shape, logprobas.shape

((10, 10), (10,))

In [4]:
configs.shape, configs_ansatze.shape, probabilities.shape

((50, 10), (50, 1), (50, 1))

### Flow

#### Standard

In [ ]:
from general_python.common.plot import MatrixPrinter

print("Detailed Flow of the Configurations:\n")
print(f"  Total number of configurations: {len(configs)}")
print(f"  Total number of states: {len(states)}")
print(f"  Total number of probabilities: {len(probabilities)}\n")

for i in range(len(configs[:3])):
    print(f"--- Configuration flow {i} ---")
    print("     Configuration \\(\\mathbf{S}_{" + f"{i}" + "}\\):")
    MatrixPrinter.print_vector(configs[i])
    
    print("    Ansatz \\(f(\\mathbf{S}_{" + f"{i}" + "})\\):")
    MatrixPrinter.print_vector(configs_ansatze[i].T)
    
    print("    Probability \\(P(\\mathbf{S}_{" + f"{i}" + "})\\):")
    MatrixPrinter.print_vector(probabilities[i].T)
    print("\n" + "-" * 50 + "\n")


Detailed Flow of the Configurations:

  Total number of configurations: 10
  Total number of states: 10
  Total number of probabilities: 10

--- Configuration flow 0 ---
     Configuration \(\mathbf{S}_{0}\):


Matrix([
[-0.5,  0.5,  0.5, -0.5,  0.5, -0.5, -0.5,  0.5,  0.5,  0.5],
[ 0.5, -0.5, -0.5,  0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5],
[ 0.5,  0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5],
[-0.5, -0.5,  0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5],
[ 0.5,  0.5, -0.5,  0.5, -0.5, -0.5,  0.5,  0.5,  0.5,  0.5],
[ 0.5,  0.5,  0.5, -0.5, -0.5,  0.5,  0.5, -0.5, -0.5,  0.5],
[-0.5, -0.5, -0.5,  0.5,  0.5,  0.5, -0.5, -0.5,  0.5,  0.5],
[-0.5,  0.5,  0.5,  0.5,  0.5, -0.5,  0.5, -0.5, -0.5,  0.5],
[-0.5, -0.5,  0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  0.5,  0.5],
[-0.5,  0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5,  0.5,  0.5]])

    Ansatz \(f(\mathbf{S}_{0})\):


Matrix([[0.243104241479246 - 0.0276354455144398*I, 0.282055377933926 + 0.352876602476411*I, 0.3079503552809 + 0.212957974552467*I, 0.250698412785718 + 0.0580381634205277*I, 0.526410725448599 + 0.0183324201182952*I, -0.109233048299867 + 0.35961465664988*I, 0.307735743708419 + 0.0361965578135887*I, 0.228253260978906 + 0.119531331580963*I, 0.252103762907549 - 0.109410936711242*I, 0.235756647884145 + 0.0862162987254024*I]])

    Probability \(P(\mathbf{S}_{0})\):


Matrix([[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]])


--------------------------------------------------

--- Configuration flow 1 ---
     Configuration \(\mathbf{S}_{1}\):


Matrix([
[ 0.5,  0.5,  0.5, -0.5,  0.5, -0.5, -0.5,  0.5,  0.5, -0.5],
[-0.5,  0.5,  0.5,  0.5,  0.5,  0.5, -0.5, -0.5, -0.5, -0.5],
[ 0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  0.5, -0.5, -0.5, -0.5],
[-0.5,  0.5,  0.5,  0.5,  0.5,  0.5, -0.5,  0.5,  0.5, -0.5],
[-0.5,  0.5,  0.5,  0.5,  0.5,  0.5, -0.5,  0.5, -0.5,  0.5],
[-0.5, -0.5, -0.5,  0.5, -0.5,  0.5, -0.5,  0.5,  0.5, -0.5],
[-0.5, -0.5, -0.5, -0.5,  0.5,  0.5, -0.5,  0.5,  0.5,  0.5],
[-0.5, -0.5, -0.5,  0.5,  0.5, -0.5, -0.5,  0.5, -0.5,  0.5],
[-0.5,  0.5,  0.5, -0.5, -0.5,  0.5, -0.5,  0.5,  0.5,  0.5],
[ 0.5,  0.5, -0.5, -0.5, -0.5, -0.5,  0.5, -0.5,  0.5, -0.5]])

    Ansatz \(f(\mathbf{S}_{1})\):


Matrix([[0.10632535920785 + 0.0681857654773016*I, -0.422451718253746 + 0.0886478375884673*I, 0.476758100906728 + 0.147500106389363*I, 0.388247997470647 + 0.270710617466821*I, -0.0800576705415127 + 0.122886646171274*I, 0.366300255179672 + 0.0783994057970958*I, 0.220521135566913 + 0.143159362726003*I, 0.25214479619002 + 0.199821679519959*I, 0.379720868264184 - 0.0732317785944154*I, 0.431937063913073 + 0.110626791389807*I]])

    Probability \(P(\mathbf{S}_{1})\):


Matrix([[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]])


--------------------------------------------------

--- Configuration flow 2 ---
     Configuration \(\mathbf{S}_{2}\):


Matrix([
[-0.5, -0.5,  0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5,  0.5],
[ 0.5,  0.5,  0.5, -0.5, -0.5,  0.5,  0.5,  0.5, -0.5,  0.5],
[-0.5, -0.5,  0.5, -0.5, -0.5,  0.5,  0.5,  0.5, -0.5, -0.5],
[ 0.5, -0.5,  0.5,  0.5,  0.5, -0.5, -0.5,  0.5, -0.5,  0.5],
[ 0.5, -0.5, -0.5,  0.5,  0.5,  0.5, -0.5,  0.5,  0.5,  0.5],
[-0.5, -0.5,  0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5,  0.5],
[ 0.5, -0.5, -0.5, -0.5, -0.5,  0.5, -0.5, -0.5,  0.5, -0.5],
[-0.5, -0.5, -0.5,  0.5, -0.5,  0.5, -0.5,  0.5,  0.5, -0.5],
[-0.5,  0.5, -0.5, -0.5,  0.5,  0.5, -0.5, -0.5,  0.5, -0.5],
[ 0.5,  0.5, -0.5, -0.5, -0.5, -0.5,  0.5,  0.5, -0.5, -0.5]])

    Ansatz \(f(\mathbf{S}_{2})\):


Matrix([[0.15391040912383 - 0.00805339345866561*I, 0.0590200733773755 + 0.0523173342114108*I, 0.40096887254246 - 0.258434550634401*I, 0.138569076872519 + 0.0912308759591849*I, 0.349721033882914 + 0.0339469961593431*I, 0.5, 0.246035163522159 + 0.0827719438183845*I, 0.366300255179672 + 0.0783994057970958*I, 0.178870634719293 + 0.273478194266899*I, 0.532410244929099 + 0.07034630418558*I]])

    Probability \(P(\mathbf{S}_{2})\):


Matrix([[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]])


--------------------------------------------------



#### Flattened

In [ ]:
from general_python.common.plot import MatrixPrinter

# -----------------------------------------------------------------
# Flatten the configurations and ansatz arrays with a clearer mathematical description
#
# Let 𝒞 ∈ ℝ^(N×d) represent the configuration matrix, where:
#   N = number of samples (configurations)
#   d = st_shape[0] (the dimension of each configuration)
#
# Similarly, for the ansatz values f(𝒞) (one per configuration), we flatten the array.
# -----------------------------------------------------------------

# Reshape configurations to a 2D array: each row is one configuration vector.
configs_flat = configs.reshape(-1, st_shape[0])
print("Shape of flattened configurations (𝒞):", configs_flat.shape)

# Flatten the ansatze: each configuration has a single ansatz value.
configs_ansatze_flat = configs_ansatze.reshape(-1)
print("Shape of flattened ansatze (f(𝒞)):", configs_ansatze_flat.shape)

print("\nDetailed flow of the configurations:")
print("Number of configurations:", len(configs_flat))
print()

# -----------------------------------------------------------------
# For the first 5 configurations, print:
#   - The configuration vector 𝒞ᵢ
#   - The ansatz from the network f(𝒞ᵢ)
#   - A verification whether f(𝒞ᵢ) matches the ansatz given by the sampler.
# -----------------------------------------------------------------
for i in range(len(configs_flat[:5])):
    print(f"--- Configuration {i} ---")
    
    print("\tConfiguration (𝒞):")
    print("\t", configs_flat[i])
    # MatrixPrinter.print_vector(configs_flat[i]
    
    print("'\tAnsatz from sampler (f(𝒞)):")
    # Compute the ansatz from the network using the configuration.
    print("\t", configs_ansatze_flat[i])
    ansatz_net = net(configs_flat[i])
    print("\tAnsatz from the network:")
    print("\t", ansatz_net)
    
    # Verify if the network's ansatz equals the sampler's ansatz.
    is_same = np.allclose(ansatz_net, configs_ansatze_flat[i])
    print("\tVerification (f(𝒞) from network ?= sampler's ansatz):", is_same)
    
    print("\n-------------------------\n")


Shape of flattened configurations (𝒞): (100, 10)
Shape of flattened ansatze (f(𝒞)): (100,)

Detailed flow of the configurations:
Number of configurations: 100

--- Configuration 0 ---
	Configuration (𝒞):
	 [-0.5  0.5  0.5 -0.5  0.5 -0.5 -0.5  0.5  0.5  0.5]
'	Ansatz from sampler (f(𝒞)):
	 (0.24310424147924645-0.027635445514439767j)
	Ansatz from the network:
	 [0.24310424-0.02763545j]
	Verification (f(𝒞) from network ?= sampler's ansatz): True

-------------------------

--- Configuration 1 ---
	Configuration (𝒞):
	 [ 0.5 -0.5 -0.5  0.5  0.5 -0.5 -0.5  0.5 -0.5 -0.5]
'	Ansatz from sampler (f(𝒞)):
	 (0.2820553779339259+0.35287660247641084j)
	Ansatz from the network:
	 [0.28205538+0.3528766j]
	Verification (f(𝒞) from network ?= sampler's ansatz): True

-------------------------

--- Configuration 2 ---
	Configuration (𝒞):
	 [ 0.5  0.5  0.5 -0.5 -0.5  0.5 -0.5 -0.5  0.5 -0.5]
'	Ansatz from sampler (f(𝒞)):
	 (0.3079503552809001+0.2129579745524674j)
	Ansatz from the network:
	 [0.30795036+0.

## Solver class

In [3]:
import NQS.nqs as nqsmodule
import Solver.MonteCarlo.sampler as Sampling
from Algebra.Model.dummy import DummyHamiltonian
from general_python.algebra.utils import get_backend
from general_python.ml.net_impl.net_simple import SimpleNet

import random
import numpy as np

# get random backend
backend             = 'np'
seed                = 1701
dtypex              = complex
be_modules          = get_backend(backend, random=True, seed=seed, scipy=True)
backend_np, (rng, rng_k), backend_sp = be_modules if isinstance(be_modules, tuple) else (be_modules, (None, None), None)

# get the network
ns                  = 2
st_shape            = (ns, )
activations         = ('relu', 'sigmoid')
net                 = SimpleNet(act_fun =   activations, 
                        input_shape     =   st_shape, 
                        output_shape    =   (1, ),
                        layers          =   (5, ),
                        backend         =   backend_np,
                        dtype           =   dtypex)

# get the sampler
sampler = Sampling.MCSampler(
    net         = net,
    shape       = st_shape,
    rng         = rng,
    rng_k       = rng_k,
    numchains   = 10,
    numsamples  = 50,
    sweep_steps = 10,
    backend     = backend_np,
    therm_steps = 10,
)

# get the Hamiltonian
par                 = 0.5 + 1j * 0.5
ham                 = DummyHamiltonian(hilbert_space=None, ns = ns, backend = backend, dtype = net.dtype)
batch_size          = 1

nqs = nqsmodule.NQS(
    net         = net,
    sampler     = sampler,
    hamiltonian = ham,
    lower_betas = None,
    lower_states= None,
    seed        = seed,
    beta        = 1.0,
    shape       = st_shape,
    backend     = backend_np,
    nthread     = 1,
    batch_size  = batch_size,
)

16_03_2025_04-13_34 [INFO] 		->[<class 'NQS.nqs.NQS'>] Network is holomorphic: True
16_03_2025_04-13_34 [INFO] 		->[<class 'NQS.nqs.NQS'>] Network has analytic gradient: True


#### Short test of network

In [6]:
states      = np.random.choice([-1,1], size=(10, ns), replace=True)
params      = net.get_params()
if backend == 'jax':
    import jax.numpy as jnp
    states  = jnp.array(states)
    ansatz  = net(params, states)
else:
    import numpy as np
    ansatz  = net(params, states)
ansatz = ansatz.reshape(-1, 1)
ansatz, ansatz.shape

(array([[0.97631688-0.15440721j],
        [0.48459178+0.30177162j],
        [0.35515613-0.50079351j],
        [0.40616546+0.03434956j],
        [0.97631688-0.15440721j],
        [0.97631688-0.15440721j],
        [0.40616546+0.03434956j],
        [0.40616546+0.03434956j],
        [0.40616546+0.03434956j],
        [0.97631688-0.15440721j]]),
 (10, 1))

#### Short test of sampler

In [3]:
# sample the configurations
(states, logprobas), (configs, configs_ansatze), probabilities = sampler.sample()

# flatten the configurations
configs_flat            = configs.reshape(-1, st_shape[0])
configs_ansatze_flat    = configs_ansatze.reshape(-1)
configs_ansatze.shape

(50, 10, 1)

In [4]:
# evaluate the network to test for a given config and check the match
ansatz_net = nqs(configs_flat)
ansatz_net.shape
ansatz_net

array([[0.80586313-0.01832699j],
       [0.87038858-0.03147754j],
       [0.80586313-0.01832699j],
       [1.0154514 -0.15119993j],
       [0.94425147-0.05701029j],
       [0.94425147-0.05701029j],
       [0.80586313-0.01832699j],
       [0.94425147-0.05701029j],
       [1.0154514 -0.15119993j],
       [0.80586313-0.01832699j],
       [0.87038858-0.03147754j],
       [1.0154514 -0.15119993j],
       [0.80586313-0.01832699j],
       [0.87038858-0.03147754j],
       [0.87038858-0.03147754j],
       [1.0154514 -0.15119993j],
       [0.80586313-0.01832699j],
       [0.94425147-0.05701029j],
       [1.0154514 -0.15119993j],
       [1.0154514 -0.15119993j],
       [0.94425147-0.05701029j],
       [1.0154514 -0.15119993j],
       [0.87038858-0.03147754j],
       [0.87038858-0.03147754j],
       [0.87038858-0.03147754j],
       [0.80586313-0.01832699j],
       [0.87038858-0.03147754j],
       [1.0154514 -0.15119993j],
       [1.0154514 -0.15119993j],
       [0.87038858-0.03147754j],
       [0.

In [5]:
# evaluate with different batch size
ansatz_net_batched = nqs(configs_flat, batch_size=3)
ansatz_net_batched, ansatz_net_batched.shape

(array([[0.87038858-0.03147754j],
        [0.80586313-0.01832699j],
        [0.94425147-0.05701029j],
        [0.87038858-0.03147754j],
        [0.87038858-0.03147754j],
        [0.80586313-0.01832699j],
        [0.94425147-0.05701029j],
        [1.0154514 -0.15119993j],
        [0.94425147-0.05701029j],
        [0.94425147-0.05701029j],
        [0.94425147-0.05701029j],
        [1.0154514 -0.15119993j],
        [0.87038858-0.03147754j],
        [1.0154514 -0.15119993j],
        [0.94425147-0.05701029j],
        [1.0154514 -0.15119993j],
        [0.87038858-0.03147754j],
        [0.80586313-0.01832699j],
        [0.80586313-0.01832699j],
        [0.87038858-0.03147754j],
        [1.0154514 -0.15119993j],
        [1.0154514 -0.15119993j],
        [0.94425147-0.05701029j],
        [0.80586313-0.01832699j],
        [0.87038858-0.03147754j],
        [1.0154514 -0.15119993j],
        [0.94425147-0.05701029j],
        [0.80586313-0.01832699j],
        [1.0154514 -0.15119993j],
        [0.870

#### Apply Hamiltonian to the states

In [5]:
# sample the configurations
(states, logprobas), (configs, configs_ansatze), probabilities = sampler.sample()
configs.shape, configs_ansatze.shape, probabilities.shape

((500, 2), (500, 1), (500, 1))

##### Batch size = 1

In [6]:
import general_python.ml.net_impl.utils.net_utils as net_utils

if backend == 'jax':
    import jax.numpy as jnp
    states  = jnp.array(states)
    
    applied_energies, applied_energies_m, applied_energies_std = \
        net_utils.jaxpy.apply_callable_batched_jax(
            func            = ham.get_loc_energy_jax_fun(),
            states          = configs,
            sample_probas   = probabilities,
            logprobas_in    = configs_ansatze,
            logproba_fun    = net.get_apply(use_jax=True)[0],
            parameters      = net.get_params(),
            batch_size      = batch_size
        )
else:
    import numpy as np
    applied_energies, applied_energies_m, applied_energies_std = \
        net_utils.numpy.apply_callable_batched_np(
            func            = ham.get_loc_energy_np_fun(),
            states          = configs,
            sample_probas   = probabilities,
            logprobas_in    = configs_ansatze,
            logproba_fun    = net.get_apply(use_jax=False)[0],
            parameters      = net.get_params(),
            batch_size      = batch_size
        )
        
print("applied_energies shape:", applied_energies.shape)
print("applied_energies_mean:", applied_energies_m)
print("applied_energies_std:", applied_energies_std)

applied_energies shape: (500,)
applied_energies_mean: (0.40853209640036947+0.0006961508921627984j)
applied_energies_std: 0.09967041465689612


##### Batch Size != 1

In [7]:
import general_python.ml.net_impl.utils.net_utils as net_utils

if backend == 'jax':
    import jax.numpy as jnp
    states  = jnp.array(states)
    
    applied_energies, applied_energies_m, applied_energies_std = \
        net_utils.jaxpy.apply_callable_batched_jax(
            func            = ham.get_loc_energy_jax_fun(),
            states          = configs,
            sample_probas   = probabilities,
            logprobas_in    = configs_ansatze,
            logproba_fun    = net.get_apply(use_jax=True)[0],
            parameters      = net.get_params(),
            batch_size      = 3
        )
else:
    import numpy as np
    applied_energies, applied_energies_m, applied_energies_std = \
        net_utils.numpy.apply_callable_batched_np(
            func            = ham.get_loc_energy_np_fun(),
            states          = configs,
            sample_probas   = probabilities,
            logprobas_in    = configs_ansatze,
            logproba_fun    = net.get_apply(use_jax=False)[0],
            parameters      = net.get_params(),
            batch_size      = 3
        )
        
print("applied_energies shape:", applied_energies.shape)
print("applied_energies_mean:", applied_energies_m)
print("applied_energies_std:", applied_energies_std)

applied_energies shape: (500,)
applied_energies_mean: (0.40853209640036947+0.0006961508921627984j)
applied_energies_std: 0.09967041465689612


##### Through the solver with states

In [8]:
# apply through the solver with the states
(configs, ansatze), probabilities, (v, means, stds) = nqs.evaluate_fun(
    states_and_psi  = (configs, configs_ansatze),
    probabilities   = probabilities,
    functions       = None,
    batch_size      = 3,
)
means, stds

((0.40853209640036947+0.0006961508921627984j), 0.09967041465689612)

##### Without states

In [17]:
# apply through the solver with the states
(configs, ansatze), probabilities, (v, means, stds) = nqs.evaluate_fun(batch_size = 3)
means, stds

((0.37454661753073765+0.0018528518164046288j), 0.06992249086177382)

In [14]:
configs.shape, ansatze.shape, probabilities.shape

((500, 2), (500, 1), (500, 1))

#### Test flax networks

In [1]:
import NQS.nqs as nqsmodule
import Solver.MonteCarlo.sampler as Sampling
from Algebra.Model.dummy import DummyHamiltonian
from general_python.algebra.utils import get_backend
from general_python.ml.net_impl.net_simple_flax import FlaxSimpleNet

import random
import numpy as np
import jax.numpy as jnp

# get random backend
backend             = 'jax'
seed                = 1701
dtypex              = jnp.complex128
be_modules          = get_backend(backend, random=True, seed=seed, scipy=True)
backend_np, (rng, rng_k), backend_sp = be_modules if isinstance(be_modules, tuple) else (be_modules, (None, None), None)

# get the network
ns                  = 10
st_shape            = (ns, )
activations         = ('relu', 'relu', 'sigmoid')
net                 = FlaxSimpleNet(act_fun =   activations, 
                            input_shape     =   st_shape, 
                            output_shape    =   (1, ),
                            layers          =   (5, ),
                            backend         =   backend_np,
                            bias            =   True,
                            dtype           =   dtypex)

# get the sampler
sampler = Sampling.MCSampler(
    net         = net,
    shape       = st_shape,
    rng         = rng,
    rng_k       = rng_k,
    numchains   = 10,
    numsamples  = 20,
    sweep_steps = 10,
    backend     = backend_np,
    therm_steps = 10,
)

# get the Hamiltonian
par                 = 0.5 + 1j * 0.5
ham                 = DummyHamiltonian(hilbert_space=None, ns = ns, backend = backend, dtype = net.dtype)
batch_size          = 1

nqs = nqsmodule.NQS(
    net         = net,
    sampler     = sampler,
    hamiltonian = ham,
    lower_betas = None,
    lower_states= None,
    seed        = seed,
    beta        = 1.0,
    shape       = st_shape,
    backend     = backend_np,
    nthread     = 1,
    batch_size  = batch_size,
)

=== Backend Initialization ===
	NumPy Version: 1.26.4
	SciPy Version: 1.13.1
	JAX Version: Not Available
		Active Backend: jax
		JAX Available: True
		Default Random Key: [    0 12345]
	Active Backend Modules:
			Main Module: <module 'jax.numpy' from '/Users/makskliczkowski/miniconda3/lib/python3.12/site-packages/jax/numpy/__init__.py'>
			Random Module: <module 'jax.random' from '/Users/makskliczkowski/miniconda3/lib/python3.12/site-packages/jax/random.py'>
			SciPy Module: <module 'jax.scipy' from '/Users/makskliczkowski/miniconda3/lib/python3.12/site-packages/jax/scipy/__init__.py'>
=== End of Backend Info ===


16_03_2025_05-05_32 [INFO] Log file created: ./log/global.log
16_03_2025_05-05_32 [INFO] Log level set to: info
16_03_2025_05-05_32 [INFO] ########### Global logger initialized. ###########
16_03_2025_05-05_33 [INFO] 		->[<class 'NQS.nqs.NQS'>] Network is holomorphic: True
16_03_2025_05-05_33 [INFO] 		->[<class 'NQS.nqs.NQS'>] Network has analytic gradient: False


##### Test the ansatz again

In [39]:
import jax.numpy as jnp
states      = np.random.choice([-1,1], size=(10, ns), replace=True)
params      = net.get_params()
states      = jnp.array(states)
ansatz      = net(params, states)
ansatz      = ansatz.reshape(-1, 1)
ansatz, ansatz.shape

(DeviceArray([[ 0.72080193-0.86857551j],
              [-0.82569107-2.11699935j],
              [ 0.97974321-1.41615628j],
              [-1.44893074-0.37550699j],
              [ 0.        +0.j        ],
              [-1.35859725+0.67320373j],
              [ 2.61938815+1.50059734j],
              [ 2.52365974-2.17150798j],
              [-1.52135902+0.75721399j],
              [ 0.        +0.j        ]], dtype=complex128),
 (10, 1))

##### Check the params

In [18]:
params      = net.get_params()

k0 = params['params']['Dense_0']['kernel']
b0 = params['params']['Dense_0']['bias']
k1 = params['params']['Dense_1']['kernel']
b1 = params['params']['Dense_1']['bias']
print("dense 0:", (k0.shape, b0.shape))
print("dense 1:", (k1.shape, b1.shape))
params['params']


dense 0: ((10, 5), (5,))
dense 1: ((5, 1), (1,))


FrozenDict({
    Dense_0: {
        kernel: DeviceArray([[ 0.12601012+0.43527496j, -0.40719852-0.02396903j,
                      -0.02069216-0.41849422j, -0.1801814 +0.0237809j ,
                       0.21579173-0.46348858j],
                     [-0.00871107+1.00927341j, -0.11819883-0.60234469j,
                       0.63919055-0.45272762j,  0.58406621+0.08718889j,
                      -0.31506518-0.35852423j],
                     [ 0.24430594-0.64656711j, -0.29367188-0.01454458j,
                       0.14447711-0.17341225j,  0.09099653-0.05758227j,
                       0.35839656-0.19071792j],
                     [ 0.25249091-0.29745224j, -0.24840753-0.58038646j,
                      -0.05843085+0.18895108j, -0.04986859+0.08540604j,
                      -0.00159741-0.19872928j],
                     [ 0.01937185-0.37934551j,  0.52302849+0.25854084j,
                      -0.85662991+0.05784103j,  0.31808552+0.12186194j,
                       0.76653099+0.31128621j],
    

##### Run the example

In [76]:
import general_python.ml.net_impl.net_simple_flax as simple_flax
simple_flax.example()

DeviceArray([[1.310566],
             [1.310566],
             [1.310566],
             [1.310566],
             [1.310566]], dtype=float32)

##### Evaluate through solver

In [2]:
# apply through the solver with the states
(configs, ansatze), probabilities, (v, means, stds) = nqs.evaluate_fun(batch_size = 10)
means, stds

(Array(95.45151426-7.19476556j, dtype=complex128),
 Array(54.57873613, dtype=float64))

##### Check whether one can calculate the gradient for the energies directly

In [3]:
import jax

def loss_fn(params):
    # recompute v with the given parameters
    (configs, ansatze), probabilities, (v, means, stds) = nqs.evaluate_fun(batch_size=10)
    return means
params      = net.get_params()
grad_loss   = jax.grad(loss_fn, holomorphic=True)(params)
print(grad_loss)

{'params': {'Dense_0': {'bias': Array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j], dtype=complex128), 'kernel': Array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]], dtype=complex128)}, 'Dense_1': {'bias': Array([0.+0.j], dtype=complex128), 'kernel': Array([[0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]], dtype=complex128)}}}


##### Check whether one can calculate the gradient for the ansatz

In [4]:
# apply through the solver with the states
(configs, ansatze), probabilities, (v, means, stds) = nqs.evaluate_fun(batch_size = 10)
means, stds, configs.shape, ansatze.shape, probabilities.shape

(Array(96.54946779-1.110614j, dtype=complex128),
 Array(49.80888498, dtype=float64),
 (200, 10),
 (200, 1),
 (200, 1))

In [5]:
import general_python.ml.net_impl.utils.net_utils as net_utils
import jax 
# create the batches
sb              = net_utils.jaxpy.create_batches_jax(configs, batch_size = 3)
print(sb.shape)
apply_f, params = net.get_apply(use_jax=True)
print(apply_f(params, sb[0]).shape)

# compute the gradients using JAX's vmap and scan
# use the provided flat_grad_fun to compute the gradients
# this is a function that computes the gradients of the network
def scan_fun(c, x):
    return c, jax.vmap(lambda y: net_utils.jaxpy.flat_gradient_holo_numerical_jax(apply_f, params, y), in_axes=(0,))(x)

# use jax's scan to compute the gradients of the logarithmic wave function
g = jax.lax.scan(scan_fun, None, sb)[1]
g = jax.tree.map(lambda x: x.reshape((-1,) + x.shape[2:]), g)
g = jax.tree.map(lambda x: x[:configs.shape[0]], g)

# # g = jax.tree_map(lambda x: x / jax.lax.norm(x), g)
g.shape

(67, 3, 10)
(3, 1)


(200, 122)

In [ ]:
# through the solver
g = nqs.gradient(configs, batch_size=3)
g.shape

(200, 122)

##### Try out standard gradient vector

In [37]:
samples     = v.shape[0]
e_centered  = (v - means)

# derivatives centered
g_means     = jnp.mean(g, axis = 0)
g_means.shape, e_centered.shape

((122,), (200,))

In [38]:
g_centered  = g - g_means
g_centered.shape

(200, 122)

In [39]:
# get F
F = jnp.matmul(jnp.conj(g_centered).T, e_centered) / samples
F.shape

(122,)

##### Try out Stochastic Reconfiguration and gradient parameter

In [40]:
# try out stochastic reconfiguration
samples = v.shape[0]
v.shape, g.shape

((200,), (200, 122))

In [41]:
e_centered  = (v - means)

# derivatives centered
g_means     = jnp.mean(g, axis = 0)
g_means.shape, e_centered.shape

((122,), (200,))

In [42]:
g_centered  = g - g_means
g_centered.shape

(200, 122)

In [45]:
g_centered_c_t = jnp.conj(g_centered).T

In [46]:
# get F
F = jnp.matmul(g_centered_c_t, e_centered) / samples
F.shape

(122,)

In [ ]:
S = jnp.matmul(g_centered_c_t, g_centered) / samples
S.shape

Array([[ 0.22801837+0.j        , -0.01618666-0.02846602j,
        -0.00134412+0.00622283j, ..., -0.00374585+0.02708472j,
        -0.00216296+0.11424091j,  0.03021412-0.16358807j],
       [-0.01618666+0.02846602j,  0.13300924+0.j        ,
         0.02886751+0.02582179j, ...,  0.02460985-0.00376554j,
         0.05937781+0.05653764j, -0.00348765+0.04406207j],
       [-0.00134412-0.00622283j,  0.02886751-0.02582179j,
         0.16402487+0.j        , ...,  0.05049501-0.07906188j,
         0.09068791-0.03088235j, -0.10974173+0.05999611j],
       ...,
       [-0.00374585-0.02708472j,  0.02460985+0.00376554j,
         0.05049501+0.07906188j, ...,  0.21315815+0.j        ,
         0.08184417+0.04798094j, -0.08648068-0.0244206j ],
       [-0.00216296-0.11424091j,  0.05937781-0.05653764j,
         0.09068791+0.03088235j, ...,  0.08184417-0.04798094j,
         0.38596167+0.j        , -0.22332059-0.01906092j],
       [ 0.03021412+0.16358807j, -0.00348765-0.04406207j,
        -0.10974173-0.05999611

In [54]:
# use standard solver
dF = jnp.linalg.pinv(S, 1e-5) * F
dF.shape
dF

Array([[  8.9141501 +6.52370340e+01j,  -0.08970477-3.34368356e-02j,
         -1.22922783+1.32414244e+00j, ...,  -4.61860888+3.36521083e+00j,
        -21.36001742-5.19873854e+01j,   0.98879088-2.11995565e+00j],
       [  0.24669341+9.88853614e-02j, -14.3407156 +1.20049590e+01j,
          0.59358664+1.88205021e+00j, ...,   5.98525745+5.62336921e+00j,
         -7.08353111-3.58099375e+00j,   2.57079673+2.61863295e+00j],
       [ -6.9567763 +2.52784760e+00j,   0.41807873-2.88199325e+00j,
         -9.2436681 -5.48470375e+00j, ...,  13.45865973+9.23173716e-01j,
          4.29972507-1.43377939e+00j,   8.17895557+3.92367686e+00j],
       ...,
       [ -4.20468346-1.85316008e+00j,   2.37664918+9.71155485e-02j,
         -1.00242766+2.45067670e+00j, ...,  -4.5931735 -5.82045092e+01j,
         -2.1897349 -6.18360740e+00j,  -0.36325874-1.27370594e+00j],
       [-27.14249801-9.56058112e+00j,   0.68942375-1.29134497e+00j,
         -0.33317713-4.58121073e-01j, ...,   3.92923431+1.41745157e+00j,
       

In [ ]:
# check my solvers
import general_python.algebra.solver as Solvers